name: Günlük EPG Güncelleme

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı (UTC)
  workflow_dispatch:     # Elle tetikleme desteği

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Repo klonla
      uses: actions/checkout@v4

    - name: Python kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Bağımlılıkları yükle
      run: pip install requests

    - name: EPG verisini indir
      run: python update_epg.py

    - name: Değişiklikleri GitHub'a gönder
      run: |
        git config user.name "epg-bot"
        git config user.email "bot@example.com"
        git add epg.xml
        git commit -m "🔄 EPG otomatik güncellendi" || echo "Değişiklik yok"
        git push
