name: EPG Uyumlu M3U ve Kanal Adı Düzeltici

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  m3u-generator:
    runs-on: ubuntu-latest
    steps:
      - name: Repo klonla
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: requests modülü
        run: pip install requests

      - name: M3U EPG eşle ve kanal adlarını düzelt
        run: |
          python epg_matcher.py

      - name: Commit et ve pushla
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "epg-bot"
          git config --global user.email "epg@bot.com"
          git add m3u-epg.m3u || echo "Dosya yok"
          git commit -m "🔄 Kanal adları ve EPG ile güncellenmiş m3u oluşturuldu" || echo "Değişiklik yok"
          git push origin main || echo "Push yok"
